# Generated by Django 5.2.8 on 2025-11-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='is_default',
        ),
    ]
