# Generated by Django 5.2.8 on 2025-11-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_deliveryaddress_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='state',
            new_name='district',
        ),
    ]
