# Generated by Django 5.2.8 on 2025-11-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
